export const icons = {
    location: require('../assets/icons/location.png'),
    heart: require('../assets/icons/heart.png'),
    message: require('../assets/icons/message.png'),
    time: require('../assets/icons/time.png'),
    verified: require('../assets/icons/verified.png'),
    whatsapp: require('../assets/icons/whatsapp.png'),
    tick: require('../assets/icons/tick.png'),
    accordion: require('../assets/icons/accordion.png'),
    calendar: require('../assets/icons/calendar.png'),
    back: require('../assets/icons/back.png'),
    home: require('../assets/icons/home.png'),
    profile: require('../assets/icons/profile.png'),
    report: require('../assets/icons/report.png'),
    privacyPolicy: require('../assets/icons/privacy_policy.png'),
    support: require('../assets/icons/support.png'),
    tnc: require('../assets/icons/terms_and_condition.png'),
};
